<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="shopify-api-key" content="{{ $apiKey }}">
<meta name="shop-domain" content="{{ $shop }}">
<title>SaleSnap</title>
<link rel="stylesheet" href="/app.css">
<script src="https://cdn.shopify.com/shopifycloud/app-bridge.js"></script>
<script defer src="/app.js"></script>
</head>
<body>
<header class="topbar"><button type="button" class="mobile-menu-toggle" id="mobile-nav-toggle" aria-label="Open app navigation" aria-controls="app-navigation" aria-expanded="false">☰</button><div class="brand"><span class="brand-icon">S</span><strong>SaleSnap</strong></div><div class="top-context">Shopify Admin &nbsp;›&nbsp; Apps</div><div class="account"><span class="status-dot"></span><span id="shop-name">{{ $shop }}</span></div></header>
<div class="mobile-nav-overlay" id="mobile-nav-overlay" aria-hidden="true"></div>
<div class="shell">
<aside class="sidebar" id="app-navigation" aria-label="SaleSnap navigation"><div class="store-card"><span class="store-avatar">{{ strtoupper(substr($shop, 0, 1)) }}</span><span><small>STORE</small><strong>{{ $shop }}</strong></span></div><div class="nav-caption">SALESNAP</div>
<button class="nav active" data-page="overview"><span>▦</span> Overview</button><button class="nav" data-page="campaigns"><span>◷</span> Campaigns</button><button class="nav" data-page="products"><span>▧</span> Products</button><button class="nav" data-page="snapshots"><span>⟲</span> Snapshots &amp; restores</button><button class="nav" data-page="activity"><span>☷</span> Activity log</button><div class="nav-rule"></div><button class="nav" data-page="settings"><span>⚙</span> Settings</button><div class="sidebar-bottom"><span class="safe-badge">✓</span><span><strong>Snapshot safeguards</strong><small>Before campaign writes</small></span></div>
</aside>
<main class="main">
<div class="page-heading"><div><div class="crumb">Apps / SaleSnap</div><h1 id="page-title">SaleSnap</h1><p id="page-desc">Schedule selected product changes with pre-change snapshots and restore reporting.</p></div><button class="primary" id="new-campaign">＋ &nbsp;Create campaign</button></div>
<div class="alert success"><span class="alert-icon">✓</span><div><strong>Pre-change snapshots</strong><p>SaleSnap saves original values before campaign writes. Check snapshot status and review any restore conflicts. <button class="text-link" data-go="snapshots">Review snapshot history</button></p></div></div>
<div id="error-banner" class="alert error hidden"></div>
<section id="overview-page">
<div class="stats"><article class="card stat"><div>Live campaigns <span class="stat-icon">◉</span></div><strong id="stat-live">—</strong><small>Running or needs attention</small></article><article class="card stat"><div>Scheduled <span class="stat-icon">◷</span></div><strong id="stat-scheduled">—</strong><small>Queued to start automatically</small></article><article class="card stat"><div>Products snapshotted <span class="stat-icon">▦</span></div><strong id="stat-protected">—</strong><small>In campaigns with snapshots</small></article><article class="card stat"><div>Completed restores <span class="stat-icon">⟲</span></div><strong id="stat-rollbacks">—</strong><small>Review restore history</small></article></div>
<div class="columns"><section class="card"><div class="section-head"><div><h2>Campaigns</h2><p>Review schedules, snapshot coverage, and restore status.</p></div><button class="quiet" data-go="campaigns">All campaigns →</button></div><div class="tabs"><button class="tab selected" data-filter="all">All</button><button class="tab" data-filter="running">Live</button><button class="tab" data-filter="scheduled">Scheduled</button><button class="tab" data-filter="completed">Completed</button></div><div id="campaign-list" class="campaign-list"><div class="loading">Loading your campaigns…</div></div></section>
<aside class="card protection"><div class="section-head"><div><h2>Snapshot &amp; restore status</h2><p>Review campaign-level snapshots and outcomes.</p></div><span class="verified">✓</span></div><div class="snapshot-latest"><div class="latest-head"><strong>Snapshot status</strong><span class="pill neutral" id="snapshot-health">Awaiting first campaign</span></div><p id="snapshot-info">A complete snapshot is required before a campaign can apply product changes.</p></div><ul class="checks"><li><b>✓</b> Snapshot saved before campaign writes</li><li><b>✓</b> Product values checked during restore</li><li><b>✓</b> Conflicts reported for review</li></ul><div class="small-note">If a value changed during a campaign, restore can skip that field and report a conflict for review.</div><button class="secondary full" data-go="snapshots">Open snapshots &amp; restore history</button></aside></div>
</section>
<section id="detail-page" class="card detail hidden"><div class="section-head"><div><h2 id="detail-title">Campaigns</h2><p id="detail-copy"></p></div></div><div id="detail-body"></div></section>
<div class="footer">Times are stored in UTC and displayed using your browser’s timezone. Product edits require Shopify Admin API access. <span id="version-label">API 2026-07</span></div>
</main></div>
<dialog id="campaign-dialog" class="dialog"><form id="campaign-form" method="dialog"><div class="dialog-head"><div><h2>Create a promotion</h2><p>Choose products, changes, and a schedule. We’ll snapshot originals first.</p></div><button type="button" class="icon-button" data-close="campaign-dialog">×</button></div><div class="form-body">
<div class="field"><label for="campaign-name">Campaign name</label><input id="campaign-name" name="name" maxlength="120" placeholder="e.g. Weekend Flash Sale" required value="Weekend Flash Sale"></div>
<div class="field"><label>Products <span class="required">*</span></label><div class="product-search"><input id="product-search" placeholder="Search products by title" autocomplete="off"><button type="button" class="secondary" id="search-products">Search</button></div><div class="helper">Select up to 250 products. Products with over 250 variants are skipped for safety.</div><div id="product-results" class="product-results"><div class="empty-picker">Search your catalog to choose products.</div></div><div id="selected-summary" class="selected-summary">0 products selected</div></div>
<div class="field"><label>Changes to apply</label><div class="action-box"><label class="check"><input type="checkbox" id="enable-price" checked><span>Discount price by</span></label><div class="inline-input"><input type="number" id="price-percent" min="1" max="90" value="20"><span>% off</span></div></div><div class="action-box"><label class="check"><input type="checkbox" id="enable-tag" checked><span>Add tag</span></label><input id="product-tag" value="flash-sale" maxlength="80" placeholder="flash-sale"></div><div class="action-box vertical"><label class="check"><input type="checkbox" id="enable-description" checked><span>Prepend to product description</span></label><input id="description-prefix" value="✦ Weekend Sale!" maxlength="240" placeholder="Sale announcement"></div><p class="helper">Rollback removes the exact description prefix and the added tag when absent in the original snapshot. A staff member re-adding the identical tag cannot be distinguished and may be removed. Prices restore only if they still match this campaign’s sale price.</p></div>
<div class="field"><label>Schedule</label><div class="date-grid"><div><label for="starts-at">Starts</label><input type="datetime-local" id="starts-at" required></div><div><label for="ends-at">Ends / automatic rollback</label><input type="datetime-local" id="ends-at" required></div></div><label class="field-label" for="timezone">Timezone</label><select id="timezone"></select></div>
<div id="form-error" class="form-error hidden"></div><div class="review-note"><b>Before we make changes:</b> We’ll save selected product fields and variant prices first. If a product is missing, inaccessible, or has unreadable variants, the campaign won’t apply changes.</div>
</div><div class="dialog-foot"><button type="button" class="secondary" data-close="campaign-dialog">Cancel</button><button type="submit" class="primary" id="schedule-button">Review &amp; schedule</button></div></form></dialog>
<dialog id="restore-dialog" class="dialog compact"><div class="dialog-head"><div><h2>Emergency restore</h2><p>This starts a rollback now.</p></div><button class="icon-button" data-close="restore-dialog">×</button></div><div class="form-body"><div class="restore-warning"><strong id="restore-name">Campaign restore</strong><p>Original snapshot values will be compared with the current product data. Fields changed since the promotion will be skipped and listed as conflicts, not overwritten.</p></div><label class="check confirm-check"><input type="checkbox" id="confirm-restore"><span>I understand this ends the campaign and starts restoring now.</span></label><div id="restore-error" class="form-error hidden"></div></div><div class="dialog-foot"><button class="secondary" data-close="restore-dialog">Cancel</button><button class="danger" id="confirm-restore-button">Restore from snapshot</button></div></dialog>
<div id="toast" class="toast" role="status"></div>
</body></html>
